### ISSUE TITLE
Projeto com erro de compilação

### ISSUE THREAD

**Issue by hugoestevam** [DEVin-NDD/DEVinCourses-m3p2-back-end#143]
Olá pessoal,

Aparentemente um merge realizado em _ITrainingRepository.cs_ está causando um erro na compilação. Está sendo usado o método _'ObterTotal'_ que não existe mais na interface.

Passos para reproduzir:
Abrir o Visual Studio e pressionar F5. 😃

**Comment by gf-albuquerque** [comment]
O problema foi solucionado, o erro estava apenas na branch main que estava desatualizada em relação a develop, foi feito o merge da develop para main e ela esta funcional novamente, precisando apenas ser feito um git pull na mesma.
